routes/web.php
<?php

use App\Http\Controllers\dashboard\BlogsController;
use App\Http\Controllers\dashboard\EventController;
use App\Http\Controllers\dashboard\ContactsController;
use App\Http\Controllers\dashboard\PagesController;
use App\Http\Controllers\dashboard\ProductsConttoller;
use App\Http\Controllers\dashboard\SettingsConttoller;
use App\Http\Controllers\dashboard\SlidesController;
use App\Http\Controllers\dashboard\UsersController;
use App\Http\Controllers\UserController;
use Barryvdh\Debugbar\DataCollector\EventCollector;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'dashboard' ,'as' => 'dashboard.','middleware' => 'auth'], function () {
	
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\dashboard\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\dashboard\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\dashboard\ProfileController@password']);

	Route::resources([
		'slides'	=> SlidesController::class,
		'blog' 		=> BlogsController::class,
		'pages' 	=> PagesController::class,
		'settings' 	=> SettingsConttoller::class,
		'products' 	=> ProductsConttoller::class,
		'contacts' 	=> ContactsController::class,
		'users' 	=> UsersController::class,
		'event'     => EventController::class
	]);

	Route::post('event/galeria', [EventCollector::class, 'galeria'])->name('event.galeria');

});

Route::get('/{slug?}/{content?}', function () {
    return view('index');
});

app/Http/Controllers/dashboard/BlogsController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\BlogsRequest;
use App\Models\Blogs;
use App\Models\CategoryBlogs;
use App\Models\Files;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

class BlogsController extends Controller
{

    public function index()
    {
        return view('dashboard.blog.index');
    }


    public function create()
    {
        return view('dashboard.blog.create',[
            'items' => CategoryBlogs::all()
        ]);
    }


    public function store(BlogsRequest $request)
    {
        // dd($request);

        $file = new Files;

        try {
            $file->upload($file, $request->file);
        } catch (\Throwable $th) {
            // throw $th;
            Log::error($th);
            return redirect()->back()->with('error','Erro ao cadastrar imagem!');
        }

        $request['files_id'] = $file->id;
        $request['users_id'] = auth()->user()->id;


        try {
            Blogs::create($request->all());
        } catch (\Throwable $th) {
            // throw $th;
            Log::error($th);
            return redirect()->back()->with('error','Erro ao cadastrar blog!');
        }

        return redirect()->route('dashboard.blog.index')->with('success','Blog Cadastrado com sucesso!');
    }


    public function show(Blogs $blogs)
    {
        //
    }


    public function edit(Blogs $blog)
    {
        return view('dashboard.blog.edit',[
            'item' => $blog,
            'items' => CategoryBlogs::all()
        ]);
    }


    public function update(BlogsRequest $request, Blogs $blog)
    {
        // dd($request->all());
        if($request->file):
            $file = new Files;

            try {
                // Storage::delete($blog->files->filename);
                $file->upload($file, $request->file);
            } catch (\Throwable $th) {
                throw $th;
                return redirect()->back()->with('error','Erro ao atualizar imagem!');
            }

            $request['files_id'] = $file->id;

        endif;

        try {
            $blog->update($request->all());
        } catch (\Throwable $th) {
            // throw $th;
            Log::error($th);
            return redirect()->back()->with('error','Erro ao atualizar blog!');
        }

        return redirect()->route('dashboard.blog.index')->with('success','Blog atualizado com sucesso!');
    }


    public function destroy(Blogs $blog)
    {
        try {
            Storage::delete($blog->files->filename);
        } catch (\Throwable $th) {
            //throw $th;
            Log::error($th);
            return redirect()->back()->with('error','Erro ao apagar imagem. Por favor entrar em contao com o suporte!');
        }

        try {
            $blog->delete();
        } catch (\Throwable $th) {
            // throw $th;
            Log::error($th);
            return redirect()->back()->with('error','Erro ao excluir blog!');
        }

        return redirect()->route('dashboard.blog.index')->with('success','Blog excluído com sucesso!');
    }
}

app/Http/Controllers/dashboard/ContactsController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use App\Models\Contacts;
use Illuminate\Http\Request;

class ContactsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.contacts.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Contacts  $contacts
     * @return \Illuminate\Http\Response
     */
    public function show(Contacts $contact)
    {
        $contact->read = '1';
        $contact->save();
        
        return view('dashboard.contacts.show',['item' => $contact]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Contacts  $contacts
     * @return \Illuminate\Http\Response
     */
    public function edit(Contacts $contacts)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Contacts  $contacts
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Contacts $contacts)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Contacts  $contacts
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contacts $contacts)
    {
        //
    }
}

app/Http/Controllers/dashboard/EventController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Event;
use App\Models\Files;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

class EventController extends Controller
{

    public function __invoke(Request $request)
    {
        $this->galeria($request);
        
        return response()->json(['success','Imagem cadastrado com sucesso!']);
        return back();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.event.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.event.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->file){
            $file = new Files;

            try {
                $file->upload($file, $request->file);
            } catch (\Throwable $th) {
                throw $th;
                Log::error($th);
                return redirect()->back()->with('error','Erro ao cadastrar imagem!');
            }

            $request['files_id'] = $file->id;
        }

        try {
            Event::create($request->all());
        } catch (\Throwable $th) {
            throw $th;
            Log::error($th);
            return redirect()->back()->with('error','Erro ao cadastrar Evento!');
        }

        return redirect()->route('dashboard.event.index')->with('success','Evento Cadastrado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Event $event)
    {
        return view('dashboard.event.show',[
            'item' => $event
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Event $event)
    {
        return view('dashboard.event.edit',[
            'item' => $event
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Event $event)
    {
        if($request->file):
            $file = new Files;

            try {
                Storage::delete($event->files->filename);
                $file->upload($file, $request->file);
            } catch (\Throwable $th) {
                throw $th;
                return redirect()->back()->with('error','Erro ao atualizar imagem!');
            }

            $request['files_id'] = $file->id;

        endif;

        try {
            $event->update($request->all());
        } catch (\Throwable $th) {
            // throw $th;
            Log::error($th);
            return redirect()->back()->with('error','Erro ao atualizar Evento!');
        }

        return redirect()->route('dashboard.event.index')->with('success','Evento atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    protected function galeria(Request $request): void {
        // dd($request->all());
        // $even
        // $file = new Files;
        // $file->gallery_id = auth()->user()->companies->gallery_id;    
    
        // $file->upload($file,$request->file, auth()->user()->companies->slug);
        // $file->save();

        
    }
}

app/Http/Controllers/dashboard/PagesController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use App\Models\Files;
use App\Models\Pages;
use Illuminate\Http\Request;

class PagesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.pages.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.pages.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $file = new Files;

        try {
            $file->upload($file, $request->file);
        } catch (\Throwable $th) {
            // throw $th;
            return redirect()->back()->with('error','Erro ao cadastrar imagem!');
        }

        $request['files_id'] = $file->id; 
        try {
            Pages::create($request->all());
        } catch (\Throwable $th) {
            // throw $th;
            return redirect()->back()->with('error','Erro ao cadastrar página!');
        }

        return redirect()->route('dashboard.pages.index')->with('success','Página criada com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Pages  $pages
     * @return \Illuminate\Http\Response
     */
    public function show(Pages $pages)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Pages  $pages
     * @return \Illuminate\Http\Response
     */
    public function edit(Pages $page)
    {
        return view('dashboard.pages.edit',['item' => $page]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Pages  $pages
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pages $page)
    {

        if($request->file):
            $file = new Files;

            try {
                $file->upload($file, $request->file);
            } catch (\Throwable $th) {
                // throw $th;
                return redirect()->back()->with('error','Erro ao atualizar imagem!');
            }

            $request['files_id'] = $file->id;

        endif;

        try {
            $page->update($request->all());
        } catch (\Throwable $th) {
            // throw $th;
            return redirect()->back()->with('error','Erro ao atualizar página!');
        }

        return redirect()->route('dashboard.pages.index')->with('success','Página Atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Pages  $pages
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pages $page)
    {
        try {
            $page->delete();
        } catch (\Throwable $th) {
            // throw $th;
            return redirect()->back()->with('error','Erro ao excluir página!');
        }

        return redirect()->back()->with('success','Página apagado com sucesso!');
    }
}

app/Http/Controllers/dashboard/ProfileController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProfileRequest;
use App\Http\Requests\PasswordRequest;
use App\Models\Files;
use App\Models\UsersHasFiles;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

class ProfileController extends Controller
{
    /**
     * Show the form for editing the profile.
     *
     * @return \Illuminate\View\View
     */
    public function edit()
    {
        return view('dashboard.profile.edit');
    }

    /**
     * Update the profile
     *
     * @param  \App\Http\Requests\ProfileRequest  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ProfileRequest $request)
    {
        if($request->file){
            $file = new Files;

            if(auth()->user()->hasfiles)
                auth()->user()->hasfiles->delete();
                Storage::delete(auth()->user()->hasfiles->file->filename);
            
            try {
                $file->upload($file, $request->file);

                UsersHasFiles::create([
                    'users_id' => auth()->user()->id,
                    'files_id' => $file->id
                ]);

            } catch (\Throwable $th) {
                throw $th;
                Log::error($th);
                return redirect()->back()->with('error','Erro ao cadastrar imagem!');
            }
        }
        
        auth()->user()->update($request->all());

       return redirect()->back()->with('success','Dados atualizados com sucesso.');
    }

    /**
     * Change the password
     *
     * @param  \App\Http\Requests\PasswordRequest  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function password(PasswordRequest $request)
    {

        auth()->user()->update(['password' => Hash::make($request->get('password'))]);

        return back()->with('success', 'Senha atualizada com sucesso.');
    }
}

app/Http/Livewire/Event.php
<?php

namespace App\Http\Livewire;

use App\Models\Event as ModelEvent;
use Livewire\Component;
use Livewire\WithPagination;

class Event extends Component
{
    use WithPagination;

    public $search;
    protected $queryString = ['search'];
    protected $paginationTheme = 'bootstrap';


    public function render()
    {
        return view('livewire.event',[
            'items' => ModelEvent::where('title', 'like', '%'.$this->search.'%')
                        ->orderBy('created_at','asc')
                            ->paginate(15)
        ]);
    }
}

app/View/Components/dashboard.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class dashboard extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.dashboard');
    }
}

resources/views/dashboard/event/create.blade.php
<x-dashboard>
    <x-slot name="title">{{ __('Evento / Adicionar') }}</x-slot>
    <x-slot name="header">
        {{-- @include('layouts.headers.cards') --}}
    </x-slot>
    <x-slot name="content"> 
        <div class="container-fluid mt--7">
            <div class="row">
                <div class="card w-100">
                    <!-- Card header -->
                    <div class="card-header border-0">
                        <div class="row">
                            <div class="col-8">
                                <h3 class="mb-0">Adicionar</h3>
                            </div>
                            <div class="col-4 d-flex justify-content-end">
                                <a href="javascript:history.back();" class="btn btn-danger btn-sm">Voltar</a>
                            </div>
                        </div>
                    </div>
                    <x-form action="{{ route('dashboard.event.store') }}" has-files>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-12 col-lg-8">
                                    <div class="form-group">
                                        <x-label for="Título" />
                                        <x-input name="title" class="form-control" value="{{ old('title') }}" />
                                        <x-error field="title" class="text-danger" />
                                    </div>
                                     <div class="form-group">
                                        <x-label for="Descrição" />
                                        <x-input name="description" class="form-control" value="{{ old('description') }}" />
                                        <x-error field="description" class="text-danger" />
                                    </div>
                                    <div class="form-group">
                                        <x-label for="Link" />
                                        <x-input name="link" class="form-control" value="{{ old('link') }}" />
                                        <x-error field="link" class="text-danger" />
                                    </div>
                                    <div class="form-group">
                                        <x-label for="Conteúdo" />
                                        <x-textarea name="content" class="form-control" id="content">{{ old('content') }}</x-textarea>
                                        <x-error field="content" class="text-danger" />
                                    </div>
                                </div>
                                <div class="col-12 col-lg-4">
                                    <div class="form-group">
                                        <x-label for="Imagem" /><br>
                                        <x-input name="file" type="file" id="input-image"/>
                                        <img id="imagem" class="img-fluid" src="">
                                        <x-error field="file" class="text-danger" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Card footer -->
                        <div class="card-footer py-4">
                            <nav class="d-flex justify-content-end" aria-label="...">
                                <button type="submit" class="btn btn-dark">Cadastrar</button>
                            </nav>
                        </div>
                    </x-form>
                </div>
            </div>
        </div>
    </x-slot>
</x-dashboard>

resources/views/dashboard/event/edit.blade.php
<x-dashboard>
    <x-slot name="title">{{ __('Evento / Editar') }}</x-slot>
    <x-slot name="header">
        {{-- @include('layouts.headers.cards') --}}
    </x-slot>
    <x-slot name="content"> 
        <div class="container-fluid mt--7">
            <div class="row">
                <div class="card w-100">
                    <!-- Card header -->
                    <div class="card-header border-0">
                        <div class="row">
                            <div class="col-8">
                                <h3 class="mb-0">Adicionar</h3>
                            </div>
                            <div class="col-4 d-flex justify-content-end">
                                <a href="javascript:history.back();" class="btn btn-danger btn-sm">Voltar</a>
                            </div>
                        </div>
                    </div>
                    <x-form action="{{ route('dashboard.event.update', $item) }}" has-files>
                        @method('PUT')
                        <div class="card-body">
                            <div class="row">
                                <div class="col-12 col-lg-8">
                                    <div class="form-group">
                                        <x-label for="Título" />
                                        <x-input name="title" class="form-control" value="{{ $item->title }}" />
                                        <x-error field="title" class="text-danger" />
                                    </div>
                                     <div class="form-group">
                                        <x-label for="Descrição" />
                                        <x-input name="description" class="form-control" value="{{ $item->description }}" />
                                        <x-error field="description" class="text-danger" />
                                    </div>
                                    <div class="form-group">
                                        <x-label for="Link" />
                                        <x-input name="link" class="form-control" value="{{ $item->link }}" />
                                        <x-error field="link" class="text-danger" />
                                    </div>
                                    <div class="form-group">
                                        <x-label for="Conteúdo" />
                                        <x-textarea name="content" class="form-control" id="content">{{ $item->content }}</x-textarea>
                                        <x-error field="content" class="text-danger" />
                                    </div>
                                </div>
                                <div class="col-12 col-lg-4">
                                    <div class="form-group">
                                        <x-label for="Imagem" /><br>
                                        <x-input name="file" type="file" id="input-image"/>                                        
                                        <img id="imagem" class="img-fluid" src="{{ $item->files ? Storage::url($item->files->filename) : null }}">
                                        <x-error field="file" class="text-danger" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Card footer -->
                        <div class="card-footer py-4">
                            <nav class="d-flex justify-content-end" aria-label="...">
                                <button type="submit" class="btn btn-dark">Atualizar</button>
                            </nav>
                        </div>
                    </x-form>
                </div>
            </div>
        </div>
    </x-slot>
</x-dashboard>

resources/views/dashboard/event/index.blade.php
<x-dashboard>
    <x-slot name="title">{{ __('Eventos') }}</x-slot>
    <x-slot name="header">
        {{-- @include('layouts.headers.cards') --}}
    </x-slot>
    <x-slot name="content"> 
        <div class="container-fluid mt--7">
            <div class="row">
                @livewire('event')
            </div>
            <div class="row mt-5">

            </div>
        </div>
    </x-slot>
</x-dashboard>

resources/views/dashboard/event/show.blade.php
<x-dashboard>
    <x-slot name="title">{{ __('Eventos / '.$item->title.' / Galeria') }}</x-slot>
    <x-slot name="header">
        {{-- @include('layouts.headers.cards') --}}
    </x-slot>
    <x-slot name="css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.4.0/min/dropzone.min.css">
        <style>
            .gallery{
                height: 200px;
            }
        </style>
    </x-slot>
    <x-slot name="content"> 
        <div class="container-fluid mt--7">
            <div class="row">
                <div class="card w-100">
                <!-- Card header -->
                <div class="card-header border-0">

                    <div class="row">
                        <div class="col-12 col-sm-3 col-md-3 col-lg-4 col-xl-7">
                            <h3 class="mb-0">Adicionar Fotos do Evento (Precisa refatorar)</h3>
                        </div>
                    </div>
                </div>
                
                <div class="card-body">
                    <form method="post" action="{{ route('dashboard.event.galeria') }}" enctype="multipart/form-data"
                        class="dropzone" id="my-dropzone">
                        <input type="hidden" name="event" value="{{ $item->id }}">
                        @csrf
                    </form>

                    <div class="row pt-5">
                        {{--  @foreach ($gallerys as $item)
                            <div class="col-12 col-sm-6 col-md-3 col-lg-3 pb-4">
                                {{ deleteButton(route('ae.galeria.destroy', $item->id)) }}
                                <img src="{{ Storage::url($item->filename) }}" class="w-100 img-fluid gallery"
                                    data-dz-remove>
                            </div>
                        @endforeach  --}}
                    </div>
                </div>
            </div>
        </div>
    </x-slot>
    <x-slot name="js">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.4.0/dropzone.js"></script>
        <script type="text/javascript">
            const id = "{{ $item->id }}"
            Dropzone.options.dropzone = {
                maxFilesize: 1,
                renameFile: function(file) {
                    var dt = new Date();
                    var time = dt.getTime();
                    return time + file.name;
                },
                acceptedFiles: ".jpeg,.jpg,.png",
                addRemoveLinks: true,
                timeout: 50000,
                removedfile: function(file) {
                    var name = file.upload.filename;
                    $.ajax({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
                        },
                        type: 'POST',
                        url: '/dashboard/event/galeria',
                        data: {
                            filename: name, id: id
                        },
                        success: function(data) {
                            console.log("File has been successfully removed!!");
                        },
                        error: function(e) {
                            console.log(e)
                        }
                    });
                    var fileRef;
                    return (fileRef = file.previewElement) != null ?
                        fileRef.parentNode.removeChild(file.previewElement) : void 0;
                },

                success: function(file, response) {
                    console.log(response);
                },
                error: function(file, response) {
                    alert('error')
                }
            }
        </script>
    </x-slot>
</x-dashboard>